In [1]:
%load_ext autoreload
%autoreload 2
%load_ext autotime

import sys
sys.path.append("..")

from tqdm import tqdm
from libs import SSQADependencyReader

In [2]:
reader = SSQADependencyReader("bert-base-chinese")

time: 3.59 s


In [3]:
dataset_path = "../data/ssqa_multiple_choice_with_dependency/test.json"
dataset = reader.read(dataset_path)

time: 943 ms


In [4]:
print(0, dataset[0])
print(1, dataset[1])
print(2, dataset[2])
print(3, dataset[3])
print(4, dataset[4])

0 Instance with fields:
 	 question_with_context: TextField of length 47 with text: 
 		[[CLS], root, 班级, 公约, 在, 何时, 决定, ？, [SEP], root, 班级, 自治, 就, 是, 透过, 班会, ，, 订定, 班级, 公约, 、, 选举, 班级, 干部,
		、, 讨论, 班级, 事务, 、, 安排, 班级, 活动, ，, 学习, 自己, 管理, 班级, 事务, ，, 让, 班级, 表现, 得, 更, 好, 。, [SEP]]
 		and TokenIndexers : {'tokens': 'PretrainedTransformerMismatchedIndexer'} 
 	 edges: AdjacencyField of length 47
		with indices:
 		[(1, 6), (3, 2), (5, 4), (6, 3), (6, 5), (6, 7), (9, 17), (11, 10), (15, 14), (17, 11), (17, 12),
		(17, 13), (17, 15), (17, 16), (17, 18), (18, 23), (23, 19), (23, 20), (23, 21), (23, 22), (23, 24),
		(24, 25), (25, 27), (25, 28), (25, 29), (25, 32), (25, 33), (25, 38), (25, 39), (25, 45), (27, 26),
		(29, 31), (31, 30), (33, 35), (35, 34), (35, 37), (37, 36), (39, 40), (39, 44), (44, 41), (44, 42),
		(44, 43)]

		and labels:
 		['ROOT', 'compound:nn', 'case', 'nsubj', 'nmod:prep', 'punct', 'ROOT', 'compound:nn', 'case',
		'nsubj', 'advmod', 'cop', 'nmod:prep', 'punct', 'ccomp', 'd

[autoreload of libs.dataset_readers.ssqa_dependency_reader failed: Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/opt/conda/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/opt/conda/lib/python3.7/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../libs/dataset_readers/ssqa_dependency_reader.py", line 29, in <module>
    class SSQADependencyReader(DatasetReader):
  File "/home/user/.local/lib/python3.7/site-packages/allennlp/comm

In [27]:
from torch_geometric.data import Data, Batch

time: 1.26 ms


In [33]:
edge_index = torch.tensor([
    [0, 0, 0, 0],
    [1, 2, 3, 4],
])
x = torch.randn(5, 1)  # 5 nodes.

data = Data(x=x, edge_index=edge_index)

time: 1.96 ms


In [34]:
print(data.x)
print(data.edge_index)

tensor([[ 0.9581],
        [ 0.5231],
        [-0.3380],
        [ 0.1966],
        [-1.8652]])
tensor([[0, 0, 0, 0],
        [1, 2, 3, 4]])
time: 2.64 ms


In [37]:
batch = Batch.from_data_list([data, data])

time: 1.77 ms


In [56]:
a = torch.range(0, 9)

time: 1.75 ms


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


In [55]:
a

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

time: 3.3 ms


In [59]:
torch.stack(a.split(5)).shape

torch.Size([2, 5])

time: 3.05 ms


In [48]:
a1.shape

torch.Size([46, 2])

time: 2.93 ms


---
## Test

In [23]:
!python -m pytest tests/dataset_readers/ssqa_singlespan_test.py

[autoreload of libs.dataset_readers.ssqa_singlespan failed: Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/opt/conda/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/opt/conda/lib/python3.7/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/workspace/GNN-based SSQA/libs/dataset_readers/ssqa_singlespan.py", line 26, in <module>
    class SSQASinglespanReader(DatasetReader):
  File "/home/user/.local/lib/python3.7/site-packages/alle

============================= test session starts ==============================
platform linux -- Python 3.7.7, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /workspace/GNN-based SSQA
collected 1 item                                                               

tests/dataset_readers/ssqa_singlespan_test.py .                          [100%]

=============================== warnings summary ===============================
/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py:546
  /opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py:546: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    class IteratorBase(collections.Iterator, trackable.Trackable,

/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py:106
  /opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.

---
## Test create answer span position

In [4]:
from allennlp.data.tokenizers import Token, PretrainedTransformerTokenizer


time: 1.71 ms


In [11]:
tokenizer = PretrainedTransformerTokenizer(
            "bert-base-chinese", add_special_tokens=False,
            is_pretokenized=True
        )

TypeError: __init__() got an unexpected keyword argument 'is_pretokenized'

time: 18 ms


In [14]:
tokens = tokenizer.tokenize("班级公约由谁来订定？")

time: 1.53 ms


In [20]:
tokens[0].pos_

time: 970 µs


In [19]:
dir(tokens[0]

['__annotations__',
 '__class__',
 '__dataclass_fields__',
 '__dataclass_params__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 'dep_',
 'ent_type_',
 'idx',
 'idx_end',
 'lemma_',
 'pos_',
 'tag_',
 'text',
 'text_id',
 'type_id']

time: 3.41 ms


In [22]:
context = "We also support limiting the maximum length for the question. and rectangle"

tokenizer = PretrainedTransformerTokenizer("bert-base-cased", add_special_tokens=False)

def tokenize_slice(start: int, end: int) -> Iterable[Token]:
    text_to_tokenize = context[start:end]
    if start - 1 >= 0 and context[start - 1].isspace():
        prefix = "a "  # must end in a space, and be short so we can be sure it becomes only one token
        wordpieces = tokenizer.tokenize(prefix + text_to_tokenize)
        for wordpiece in wordpieces:
            if wordpiece.idx is not None:
                wordpiece.idx -= len(prefix)
        return wordpieces[1:]
    else:
        return tokenizer.tokenize(text_to_tokenize)

tokenized_context = []
token_start = 0
for i, c in enumerate(context):
    if c.isspace():
        for wordpiece in tokenize_slice(token_start, i):
            if wordpiece.idx is not None:
                wordpiece.idx += token_start
            tokenized_context.append(wordpiece)
        token_start = i + 1
for wordpiece in tokenize_slice(token_start, len(context)):
    if wordpiece.idx is not None:
        wordpiece.idx += token_start
    tokenized_context.append(wordpiece)
    
for tok in tokenized_context:
    print(tok, tok.idx)
    
# We 0
# also 3
# support 8
# limiting 16
# the 25
# maximum 29
# length 37
# for 44
# the 48
# question 52
# . 60
# and 62
# re 66
# ##ct 68
# ##ang 70
# ##le 73

We 0
also 3
support 8
limiting 16
the 25
maximum 29
length 37
for 44
the 48
question 52
. 60
and 62
re 66
##ct 68
##ang 70
##le 73


In [25]:
[
    (t.idx, t.idx + len(sanitize_wordpiece(t.text))) if t.idx is not None else None
    for t in tokenized_context
]

# [(0, 2),
#  (3, 7),
#  (8, 15),
#  (16, 24),
#  (25, 28),
#  (29, 36),
#  (37, 43),
#  (44, 47),
#  (48, 51),
#  (52, 60),
#  (60, 61),
#  (62, 65),
#  (66, 68),
#  (68, 70),
#  (70, 73),
#  (73, 75)]

[(0, 2),
 (3, 7),
 (8, 15),
 (16, 24),
 (25, 28),
 (29, 36),
 (37, 43),
 (44, 47),
 (48, 51),
 (52, 60),
 (60, 61),
 (62, 65),
 (66, 68),
 (68, 70),
 (70, 73),
 (73, 75)]

In [30]:
first_answer_offset = 16
answers = "limiting"

char_span_to_token_span(
    [
        (t.idx, t.idx + len(sanitize_wordpiece(t.text))) if t.idx is not None else None
        for t in tokenized_context
    ],
    (first_answer_offset, first_answer_offset + len(answers[0])),
)

# ((3, 3), True)

((3, 3), True)

In [34]:
len(tokenizer.sequence_pair_end_tokens)
# 1

1